%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% File: call_ESPERs.m
% Author: Reese Barrett
% Date: 2023-10-2y

% Description:
% - Reads  GLODAPv2.2022 .csv files modified for use in ESPERs
% - Calls each ESPER and runs each available equation of the 16 per ESPER
% to predict TA
% - Outputs data into format as .csv
%    
% To-Do:
% - read in .csv file
% - run through ESPERs
% - set up output to be useful (want all original properties + predicted TA
% at each lat/lon/depth/time + associated uncertainties
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% read in modified GLODAP data from .csv generated by
% glodap_data_formatting.py



%% call ESPER_LIR

%% call ESPER_NN

%% call ESPER_MIXED








